# Example 1

Write a function that takes a list as argument and outputs another list which consists of the same numbers in the original list but doubled.

In [ ]:
def f1(x):
    return

# Review of builtin data types

## Integers

These are discrete numbers with no decimal place. Integer math with other integers usually leads to integers.

In [ ]:
a = 1
b = 2

In [ ]:
a - b, a + b, a * b

(-1, 3, 2)

One exception is division. In Python3, the default division leads to floats.

In [ ]:
a / b

0.5

You have to use // to get integer division. This is *usually* not what we want in engineering programs, but if you do want it, hear is how you get it.

In [ ]:
a // b

0

## Floats

Floats are continuous numbers, often with a decimal. Floats are not exact, but are approximate. The approximation is usually very good, but there are times you should be careful.

In [ ]:
x = 0.1
f"{x:1.17f}"

'0.10000000000000001'

## Lists
Lists are a container that can hold many kinds of values. They are surrounded by [].

In [ ]:
a = ["a", 2, [2, "b"]]
a

['a', 2, [2, 'b']]

Lists are mutable. You can change them after you make them.

In [ ]:
a[0] = 1
a[2] = 3
a

[1, 2, 3]

There are limited operations you can do with a list. You can add two lists, which simply concatenates the two lists. 

In [ ]:
b = [5]
a + b

[1, 2, 3, 5]

You can multiply them by an integer, which repeates the list that many times.

In [ ]:
3 * b

[5, 5, 5]

You can append a list to a list with +=

In [ ]:
b += [6]
b

[5, 6]

You can also perform an inplace repeat like this.

In [ ]:
b *= 4
b

[5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6,
 5,
 6]

There are not many other operations you can do with math though.

## Tuples
Tuples are like lists, but are surrounded by parentheses, and they are *immutable*, which means you cannot change them after you make them. This avoids some kinds of bugs that occur when list contents change.

In [ ]:
t = (1, 2, 3)

In [ ]:
# you cannot change an element in a tuple
t[0] = 0

TypeError: ignored

Similar to lists, you can repeat and add them. 

In [ ]:
t * 2

(1, 2, 3, 1, 2, 3)

In [ ]:
t + t

(1, 2, 3, 1, 2, 3)

In [ ]:
# You can add to a tuple though. that might seem like a mutation, but items 0-2 remain the same.
t += (5,)
t

(1, 2, 3, 5)

# Numpy arrays

Numpy arrays are like lists, but you can use them for math purposes. You create them from a list, or from a numpy function.

In [ ]:
import numpy as np

n = np.array([1, 2, 3])

Most math operations are elementwise.

In [ ]:
2 + n, 2 - n

(array([3, 4, 5]), array([ 1,  0, -1]))

In [ ]:
2 * n, 2 / n

(array([2, 4, 6]), array([2.        , 1.        , 0.66666667]))

In [ ]:
# we need a function to concatenate arrays
np.concatenate((n, n))

array([1, 2, 3, 1, 2, 3])

# Avoid mutable default arguments
Why did I go to the trouble of describing mutable and immutable? Because you can run into to trouble. Here is one example of this. Suppose we write a function to collect $n$ random integers

In [ ]:
def bad_func(n=2, L=[]):
    for i in range(n):
        L += [np.random.randint(10)]
    return L

In [ ]:
bad_func()

[8, 4]

In [ ]:
bad_func()  # Surprise! you get 4 numbers, including the first two.

[8, 4, 1, 1]

In [ ]:
bad_func(n=3, L=[0, 0])  # Another surprise if you specify L.

[0, 0, 3, 1, 8]

In [ ]:
bad_func()  # And yet another surprise

[8, 4, 1, 1, 3, 5]

The big lesson here is DO NOT USE MUTABLE DEFAULT ARGUMENTS!

Here is a better way to do this.

In [ ]:
def good_func(n=2, L=None):
    if L is None:
        L = []
    for i in range(n):
        L += [np.random.randint(10)]
    return L

In [ ]:
good_func()

[2, 6]

In [ ]:
good_func()

[8, 1]

In [ ]:
good_func(L=[0, 0])

[0, 0, 8, 9]