[TOC](../toc.ipynb)

Introduction to Linear algebra
==============================

- KEYWORDS: numpy.transpose, numpy.eye, numpy.diag, numpy.tri, @, numpy.transpose, numpy.allclose, numpy.linalg.det, numpy.linalg.inv, numpy.linalg.matrix_rank, numpy.linalg.cond, numpy.linalg.solve




```{tip}
We will introduce a lot of new commands today. You should get some paper and take notes on what the are for review later.
```



![image](https://drive.google.com/uc?id=1kcH91Ew81vL4pQcrpFN5ExzLu8aNKHXy)



## Multidimensional arrays





The foundation of linear algebra in Python is in multidimensional arrays.





In [1]:
import numpy as np



We make multidimensional arrays by using lists of lists of numbers. For example, here is a 2D array:



In [2]:
A = np.array([[1, 2, 3], 
              [3, 4, 5]])
A



array([[1, 2, 3],
       [3, 4, 5]])

We can find out the shape of an array, i.e. the number of rows and columns from the shape attribute. It returns (rows, columns).





In [6]:
A.shape, np.prod(A.shape)



((2, 3), 6)

In [5]:
x = np.linspace(0, 1, 10)
x.shape

(10,)

### Constructing arrays





You can always make arrays by typing them in. There are many convenient ways to make special ones though. For example, you can make an array of all ones or zeros with these:





In [8]:
x * 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(x.shape)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(shape=[3, 3])



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(shape=[3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.ones(3)



array([1., 1., 1.])

In [12]:
x * 0 + 1 # using array algebra to make an array of ones.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

You can make an identity matrix with:



In [16]:
np.eye(N=3) 



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

or a diagonal array:





In [23]:
np.diag([3, 2, 1, 0.0]) # preferrable way to build an array



array([[3., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [22]:
Z = np.zeros([4, 4])  # tedious way to do the same
Z[0, 0] = 3
Z[1, 1] = 2
Z[2, 2] = 1
Z[3, 3] = 0

Z

array([[3., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [24]:
Z = np.zeros([4, 4]) # slightly less tedious
for i, val in enumerate([3, 2, 1, 0]):
    Z[i, i] = val
Z    

array([[3., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

If you need a lower triangular array:





In [25]:
np.tri(3)



array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

See these to manipulate existing arrays



In [26]:
?np.triu



Signature: np.triu(m, k=0)
Docstring:
Upper triangle of an array.

Return a copy of an array with the elements below the `k`-th diagonal
zeroed. For arrays with ``ndim`` exceeding 2, `triu` will apply to the
final two axes.

Please refer to the documentation for `tril` for further details.

See Also
--------
tril : lower triangle of an array

Examples
--------
>>> np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

>>> np.triu(np.arange(3*4*5).reshape(3, 4, 5))
array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  0, 12, 13, 14],
        [ 0,  0,  0, 18, 19]],
       [[20, 21, 22, 23, 24],
        [ 0, 26, 27, 28, 29],
        [ 0,  0, 32, 33, 34],
        [ 0,  0,  0, 38, 39]],
       [[40, 41, 42, 43, 44],
        [ 0, 46, 47, 48, 49],
        [ 0,  0, 52, 53, 54],
        [ 0,  0,  0, 58, 59]]])
File:      /opt/tljh/user/lib/python3.9/site-packages/numpy/lib/twodim_base.py
Type:  

In [27]:
?np.tril



Signature: np.tril(m, k=0)
Docstring:
Lower triangle of an array.

Return a copy of an array with elements above the `k`-th diagonal zeroed.
For arrays with ``ndim`` exceeding 2, `tril` will apply to the final two
axes.

Parameters
----------
m : array_like, shape (..., M, N)
    Input array.
k : int, optional
    Diagonal above which to zero elements.  `k = 0` (the default) is the
    main diagonal, `k < 0` is below it and `k > 0` is above.

Returns
-------
tril : ndarray, shape (..., M, N)
    Lower triangle of `m`, of same shape and data-type as `m`.

See Also
--------
triu : same thing, only for the upper triangle

Examples
--------
>>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

>>> np.tril(np.arange(3*4*5).reshape(3, 4, 5))
array([[[ 0,  0,  0,  0,  0],
        [ 5,  6,  0,  0,  0],
        [10, 11, 12,  0,  0],
        [15, 16, 17, 18,  0]],
       [[20,  0,  0,  0,  0],
        [25, 26, 

In [28]:
np.ones(10)



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.tril(np.ones(10), k=-3)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.]])

In [37]:
np.triu(np.ones(4), k=1)



array([[0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

Make a 10x10 array where the -3 diagonal is ones, and everything else is zero.

In [38]:
np.tril(np.ones(10), k=-3) - np.tril(np.ones(10), k=-4)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [41]:
np.diag(np.ones(7), k=-3)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [45]:
Z = np.zeros((10, 10))
for row in range(3, 10):
    for column in range(0, 7):
        if column == row - 3:
            Z[row, column] = 1
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

### Regular Algebra with arrays





It takes some getting use to how to use arrays with algebra.





#### Addition and subtraction





Let's start with addition and subtraction. A good rule to remember that you can add and subtract arrays with the same shape.





In [46]:
A = np.array([[1, 2], [3, 4]])
A



array([[1, 2],
       [3, 4]])

In [47]:
B = np.ones(A.shape)
B



array([[1., 1.],
       [1., 1.]])

In [48]:
A + B



array([[2., 3.],
       [4., 5.]])

In [49]:
A - B



array([[0., 1.],
       [2., 3.]])

This is an error though because the shapes do not match.

https://jamboard.google.com/d/16zPBsWOnT_Vkh106vWozsrT_sGYoJ5gPo_ZzyTIenE4/viewer?f=1



In [50]:
A



array([[1, 2],
       [3, 4]])

In [51]:
C = np.array([[0, 0, 1], [1, 0, 0]])
C



array([[0, 0, 1],
       [1, 0, 0]])

In [52]:
A - C



ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

Note, however, that this is ok. This feature is called *broadcasting*. It works when the thing you are adding can be added to each row.





In [53]:
C



array([[0, 0, 1],
       [1, 0, 0]])

In [56]:
d = np.array([2, 3, 4])
d.shape



(3,)

In [57]:
C + d



array([[2, 3, 5],
       [3, 3, 4]])

In [58]:
e = np.array([[3], 
              [3]])
e.shape



(2, 1)

In [59]:
C + e



array([[3, 3, 4],
       [4, 3, 3]])

To add to just one column



In [ ]:
C



In [ ]:
C[:, 1]



In [ ]:
C[:, 1] = C[:, 1] + [3, 4]



In [ ]:
C



**Exercise** Use some algebra to get an array that is ones above the main diagonal, and zeros everywhere else.





#### Multiplication and division





The default multiplication and division operators work *element-wise*.





In [ ]:
A



In [ ]:
2 * A



In [ ]:
2 / A  # element-wise division



In [ ]:
B



In [ ]:
A * B



In [ ]:
B * A



In [ ]:
B / A



In [ ]:
A / B



Similar elementwise for powers



In [ ]:
(A**2)



### Matrix algebra





To do matrix multiplication you use the @ operator (This is new in Python 3.5), or the `numpy.dot` function. If you are not familiar with the idea of matrix multiplication you should review it at [https://en.wikipedia.org/wiki/Matrix_multiplication](https://en.wikipedia.org/wiki/Matrix_multiplication).

We write matrix multiplication as: $\mathbf{A} \mathbf{B}$. We cannot multiply any two arrays; their shapes must follow some rules. We can multiply any two arrays with these shapes:

(m, c) \* (c, n) = (m, n)

In other words the number of columns in the first array must equal the number of rows in the second array. This means it is not generally true that $\mathbf{A} \mathbf{B} = \mathbf{B} \mathbf{A}$.

https://jamboard.google.com/d/16zPBsWOnT_Vkh106vWozsrT_sGYoJ5gPo_ZzyTIenE4/viewer?f=2



In [ ]:
A



In [ ]:
B



In [ ]:
A @ B  # @ is the matrix multiply operator



In [ ]:
B @ A



This is the older way to do matrix multiplication.





In [ ]:
np.dot(A, B)



These rules are true:

1.  $(k \mathbf{A})\mathbf{B} = k(\mathbf{A} \mathbf{B}) = \mathbf{A}(k\mathbf{B})$
2.  $\mathbf{A}(\mathbf{B}\mathbf{C}) = (\mathbf{A}\mathbf{B})\mathbf{C}$
3.  $(\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C}$
4.  $\mathbf{C}(\mathbf{A} + \mathbf{B}) = \mathbf{C}\mathbf{A} + \mathbf{C}\mathbf{B}$

**Exercise** construct examples of each of these rules.







In [ ]:
k = 1
m1 = (k * A) @ B
m2 = k * (A @ B)
m3 = A @ (k * B)
np.allclose(m1, m2) and (np.allclose(m2, m3))



In [ ]:
m1, m2



In [ ]:
C = np.array([[7, 8], [5, 6]])
np.allclose(A @ (B @ C), (A @ B) @ C)



In [ ]:
np.allclose((A + B) @ C, A @ B + A @ C)



We can also multiply a matrix and vector. This is like the shapes of (m, r) \* (r, 1) = (m, 1)



In [ ]:
x = np.array([1, 2])  # 1D array - Python will DWYM (do what you mean)
A @ x



There is a small subtle point, the x-array is 1-D:





In [ ]:
x, x.shape



Its shape is not (2, 1)! Numpy does the right thing here and figures out what you want. Not all languages allow this, however, and you have to be careful that everything has the right shape with them.





**Reflective Questions**



In [ ]:
from f22_06623 import MCQ
MCQ(["arrays"])



## Linear algebra functions of arrays





### The transpose





In the transpose operation you swap the rows and columns of an array. The transpose of A is denoted $\mathbf{A}^T$.

https://jamboard.google.com/d/16zPBsWOnT_Vkh106vWozsrT_sGYoJ5gPo_ZzyTIenE4/viewer?f=3



In [ ]:
A



In [ ]:
A.T



In [ ]:
np.array([[1, 2, 3], [4, 5, 6]]).T



There is also a function for transposing.





In [ ]:
np.transpose(A)



A matrix is called *symmetric* if it is equal to its transpose: $\mathbf{A} == \mathbf{A}^T$.





In [ ]:
Q = np.array([[1, 2], [2, 4]])

np.allclose(Q, Q.T)



A matrix is called *skew symmetric* if $\mathbf{A}^T = -\mathbf{A}$.





In [ ]:
Q = np.array([[0, 1], [-1, 0]])

np.allclose(Q.T, -Q)



A matrix is called *orthogonal* if this equation is true: $\mathbf{A} \mathbf{A}^T = \mathbf{I}$. Here is an example of an orthogonal matrix:





In [ ]:
theta = -10
Q = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

with np.printoptions(suppress=True):
    print(Q @ Q.T)



Here are the four rules for matrix multiplication and transposition

1.  $(\mathbf{A}^T)^T = \mathbf{A}$

2.  $(\mathbf{A}+\mathbf{B})^T = \mathbf{A}^T+\mathbf{B}^T$

3.  $(\mathit{c}\mathbf{A})^T = \mathit{c}\mathbf{A}^T$

4.  $(\mathbf{AB})^T = \mathbf{B}^T\mathbf{A}^T$

**Exercise** Come up with an example for each rule.





### The determinant





The determinant of a matrix is noted: det(A) or |A|. Many matrices are used to linearly transform vectors, and the determinant is related to the scaling magnitude.





In [ ]:
A



In [ ]:
np.linalg.det(A)  # note the linalg



### The inverse





A matrix is invertible if and only if the determinant of the matrix is non-zero.

The inverse is defined by: $\mathbf{A} \mathbf{A}^{-1} = \mathbf{I}$.

We compute the inverse as:





In [ ]:
A



In [ ]:
np.linalg.inv(A)



And here verify the definition.





In [ ]:
with np.printoptions(suppress=True):
    print(A @ np.linalg.inv(A))



In [ ]:
np.allclose(A @ np.linalg.inv(A), np.eye(2))



Another way to define an orthogonal matrix is $\mathbf{A}^T = \mathbf{A}^{-1}$.


$\mathbf{A} \mathbf{A}^T = \mathbf{I}$.

Now left multiply each side by $\mathbf{A}^{-1}$.

$\mathbf{A}^{-1} \mathbf{A} \mathbf{A}^T = \mathbf{A}^{-1} \mathbf{I}$.

which leads to:
$\mathbf{A}^T = \mathbf{A}^{-1}$



In [ ]:
theta = 12
Q = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

np.allclose(Q.T, np.linalg.inv(Q))



In [ ]:
with np.printoptions(suppress=True):
    print(Q @ Q.T)



### Rank





The rank of a matrix is equal to the number of linearly independent rows in it. Rows are linearly independent if and only if they cannot be made by constants times another row or linear combinations of other rows.





In [ ]:
?np.linalg.pinv



In [ ]:
A



In [ ]:
np.linalg.matrix_rank(A), np.linalg.det(A)



Here is an example of a rank-deficient array. The last row is a linear combination of the first two rows.

https://jamboard.google.com/d/16zPBsWOnT_Vkh106vWozsrT_sGYoJ5gPo_ZzyTIenE4/viewer?f=3



In [ ]:
A1 = [[1, 2, 3], [0, 2, 3], [2, 6, 9]]

np.linalg.matrix_rank(A1)



In [ ]:
A1 = np.array(A1)
A1[0] * 2 + A1[1]



In [ ]:
np.linalg.det(A1)



In [ ]:
np.linalg.inv(A1)



Here is an example of a *rank-deficient* array. It is deficient because the last row is just 0 times any other row.





In [ ]:
A1 = [[1, 2, 3], [0, 2, 3], [0, 0, 0]]

np.linalg.matrix_rank(A1)



Note the determinant of this array is zero as a result. These arrays are not invertible.





In [ ]:
np.linalg.det(A1)



Also note the inverse is either not defined due to being singular or it has some enormous numbers in it. This is not a reliable inverse. It is never a good idea to have giant numbers and small numbers in the same calculations!





In [ ]:
np.linalg.inv(A1)



The condition number is a measure of the norm of an array times the inverse of the array. If it is very large, the array is said to be *ill-conditioned*.





In [ ]:
np.linalg.cond(A1)



What all of these mean is that we only have two independent rows in the array.





## Solving linear algebraic equations





One of the key reasons to develop the tools above is for solving linear equations. Let's consider an example.

Given these equations, find [x1, x2, x3]

\begin{eqnarray}
x_1 - x_2 + x_3 &=& 0 \\
10 x_2 + 25 x_3 &=& 90 \\
20 x_1 + 10 x_2 &=& 80
\end{eqnarray}

reference: Kreysig, Advanced Engineering Mathematics, 9th ed. Sec. 7.3

First, we express this in the form $\mathbf{A} \mathbf{x} = \mathbf{b}$.

https://jamboard.google.com/d/16zPBsWOnT_Vkh106vWozsrT_sGYoJ5gPo_ZzyTIenE4/viewer?f=4



In [ ]:
A = np.array([[1, -1, 1], [0, 10, 25], [20, 10, 0]])

b = np.array([0, 90, 80])



In [ ]:
x = np.linalg.inv(A) @ b
x



In [ ]:
np.allclose(A @ x, b)



Now, if we *left* multiply by $\mathbf{A}^{-1}$ then we get:

$\mathbf{A}^{-1} \mathbf{A} \mathbf{x} = \mathbf{A}^{-1} \mathbf{b}$ which simplifies to:

$\mathbf{x} = \mathbf{A}^{-1} \mathbf{b}$

How do we know if there should be a solution?  First we make the augmented matrix $\mathbf{A} | \mathbf{b}$. Note for this we need $\mathbf{b}$ as a column vector. Here is one way to make that happen. We make it a row in a 2D array, and transpose that to make it a column.





In [ ]:
Awiggle = np.hstack([A, np.array([b]).T])
Awiggle



In [ ]:
np.concatenate([A, np.reshape(b, (-1, 1))], axis=1)



If the rank of $\mathbf{A}$ and the rank of $\mathbf{\tilde{A}}$ are the same, then we will have one unique solution. if the rank is less than the number of unknowns, there maybe an infinite number of solutions.





In [ ]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(Awiggle)



If $\mathbf{b}$ is not all zeros, we can also use the fact that a non-zero determinant leads to a unique solution.





In [ ]:
np.linalg.det(A)



It should also be evident that since we use an inverse matrix, it must exist (which is certain since the determinant is non-zero). Now we can evaluate our solution.





In [ ]:
x = np.linalg.inv(A) @ b
x



Now you might see why we *vastly* prefer linear algebra to nonlinear algebra; there is no guessing or iteration, we just solve the equations!

Let us confirm our solution:





In [ ]:
A @ x == b  # do not use == for float comparisons



This fails because of float tolerances:





In [ ]:
A @ x - b



We should instead see if they are all close. You could roll your own comparison, but we instead leverage `numpy.allclose` for this comparison.





In [ ]:
np.allclose(A @ x, b)



The formula we used above to solve for $\mathbf{x}$ is not commonly used. It turns out computing the inverse of a matrix is moderately expensive. For small systems it is negligible, but the time to compute the inverse grows as $N^3$, and there are more efficient ways to solve these when the number of equations grows large.

This next block takes a while to run (tens of seconds).

https://jamboard.google.com/d/16zPBsWOnT_Vkh106vWozsrT_sGYoJ5gPo_ZzyTIenE4/viewer?f=5



In [ ]:
import numpy as np
import time

t = []
I = np.array(range(2, 5001, 500))
for i in I:
    m = np.eye(i)
    t0 = time.time()
    np.linalg.inv(m)
    t += [time.time() - t0]

import matplotlib.pyplot as plt

plt.plot(I, t)
plt.xlabel("N")
plt.ylabel("Time to invert (s)");



As usual, there is a function we can use to solve this.





In [ ]:
?np.linalg.solve



In [ ]:
np.linalg.solve(A, b)



Let's check this timing.



In [ ]:
t = []
I = np.array(range(2, 5001, 500))
for i in I:
    A = np.eye(i)
    b = np.arange(i)
    t0 = time.time()
    np.linalg.solve(A, b)
    t += [time.time() - t0]


plt.plot(I, t)
plt.xlabel("N")
plt.ylabel("Time to solve Ax=b (s)");



You can see by inspection that solve must not be using an inverse to solve these equations; if it did, it would take much longer to solve them. It is remarkable that we can solve ~5000 simultaneous equations here in about 1-2 seconds!

This may seem like a lot of equations, but it isn't really. Problems of this size routinely come up in solving linear boundary value problems where you discretize the problem into a large number of linear equations that are solved.





**Reflective Questions**



In [ ]:
MCQ(["matrices"])



## Summary





Today we introduced many functions used in linear algebra. One of the main applications of linear algebra is solving linear equations. These arise in many engineering applications like mass balances, reaction network analysis, etc. Because we can solve them directly (not iteratively with a guess like with non-linear algebra) it is highly desirable to formulate problems as linear ones where possible.

There are many more specialized routines at [https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.linalg.html](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.linalg.html).





## Coding Questions



Q1. Find the solution to the following set of equations:

$x_1 + x_2 - x_3 = 9$

$3x_1 - x_2 + 2x_3 = 14$

$x_1 + 2x_2 - 3x_3 = 10$



Q2. Find the rank and determinant of the matrix in the code cell below.



In [ ]:
# given matrix
A = np.array([[1, 2, 3], [1, -1, 2], [3, 2, 1]])

# rank of the matrix
rank = 

# determinant of the matrix
det = 


